### ISSUE TITLE
Update Logger

### ISSUE THREAD

**Issue by imWillX** [Hazebyte/CrateReloaded#270]
Update logger with support for in-game menu

**Comment by mibby** [comment]
Would it be possible to update the logger to find out how someone obtained a key too in their claim file? I got users who are receiving keys in their claim storage but not sure how. Many of the keys they have require them to kill mobs in a world while online, which should give them the key directly rather than put in their storage.

Unless if their inventory is full, the key goes directly to their claim instead of dropping on the ground in front of them like in 1.x?

**Comment by mibby** [comment]
Would it be possible to also add an option to not go in to the claim when the inventory is full and instead just drop in front of the player like before?
