### ISSUE TITLE
Interaction Error

### ISSUE THREAD

**Issue by ZEROOblivious** [Hazebyte/CrateReloaded#455]
https://pastebin.com/A2Vb9rNv

Server Version: Paper-Spigot
Plugin Version: 2.0.24_hotfix

This is when someone uses a key on the crate. I did some tests removing the crates, removing a lot of the data, moving the crates to a different location, removed the animation from the crate so it will just give the reward.

**Comment by imWillX** [comment]
Closing this issue. 

The issuer has mentioned that the error log is a result of another plugin called SoundMuffler (https://thebusybiscuit.github.io/builds/J3fftw1/SoundMuffler/master/). Crash logs show that this plugin crashes on Player#UpdateInventory which should be fine as called. Since the plugin works fine without SoundMuffler, I will be closing this issue.
