### ISSUE TITLE
Key Crate: Confirmation Menu

### ISSUE THREAD

**Issue by imWillX** [Hazebyte/CrateReloaded#46]
![confirmation](https://proxy.spigotmc.org/784ce4d808b1b21f989a1e4d4622c1d4041c43cf?url=https%3A%2F%2Fgyazo.com%2F5df476fa4e737c1ca879077b31db9379.png)

**Comment by mibby** [comment]
Would it be possible to have an option to enable a confirmation window on keys used at a set CSGO roulette crate location? Since if you have creative-control enabled, it automatically uses a key if you right click the crate, even if not holding the key. People may accidentally use up a key they may not want to use.
